In [1]:
import sys
import argparse
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import convolve1d

In [7]:
def rgb2gray(img_color) :

    # input:
    #    img_color - a h x w x 3 numpy ndarray (dtype = np.unit8) holding
    #                the color image
    # return:
    #    img_gray - a h x w numpy ndarray (dtype = np.float64) holding
    #               the grayscale image

    # TODO: using the Y channel of the YIQ model to perform the conversion
    
    
    img_gray = np.dot(img_color[..., :3], [0.299, 0.587, 0.114])
    # def temp(channels):
    #     return np.dot(channels, [0.299, 0.587, 0.114])
    # img_gray = np.apply_along_axis(temp, -1, img_color)

    return img_gray
# a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
# print(rgb2gray(a))

[[1.815 4.815 7.815]
 [1.815 4.815 7.815]
 [1.815 4.815 7.815]]
